Update 9_tips-and-tricks.md
gridai/grid-docs pull request #258
Opened 2022-05-17 17:13 UTC by sunitaprakash

Add a Trick to stop a run after X no of hours

# What does this PR do?

Explain purpose of PR and any useful context.

2022-05-17 19:48 UTC, oojo12 requested changes

2022-05-17 19:48 UTC, oojo12 commented on docs/platform/9_tips-and-tricks.md
> +As a convenience, we provide a [GitHub Action](https://github.com/sunitaprakash/gridai-stop-run) for stopping a Run that has been running for X no of hours.
please set this to a Grid org repo. If you don't have permissions to do this I can for you.

2022-05-18 18:39 UTC, oojo12 approved these changes

2022-05-23 22:12 UTC, essiequoi approved these changes

2022-05-23 22:13 UTC, merged