Documentation Updates
gridai/grid-docs pull request #76
Opened 2021-12-08 19:30 UTC by oojo12

This PR is an attempt to make various documentation updates spanning the following areas:

- [ ]  Updating the multi-node documentation with a public repo and self-containing instructions for running it
- [ ] Expand upon grid status documentation
- [ ] Add potential resolution to windows pathing issue to FAQ
- [ ] Update examples in tutorial sections to be from gridai repos

Resolves: SUP-136

2021-12-15 00:43 UTC, essiequoi requested changes
Hey @oojo12 finished review, please take a look at comments

2021-12-15 00:43 UTC, essiequoi commented on platform/about-these-features/multi-node.md
>  For example --gpus 5 --instance\_type 4\_v100\_32gb will automatically trigger multi node training
change --gpus 5 to --gpus 8

2021-12-15 00:43 UTC, essiequoi commented on platform/about-these-features/multi-node.md
> +Example of 1 node 1 GPU :
@oojo12 can you explain the change here? and in the other examples?

2021-12-15 00:43 UTC, essiequoi commented on platform/about-these-features/multi-node.md
>  ```
@oojo12 nice! i'm assuming you tested this out? we should add a screenshot of the completed experiment

2021-12-15 00:43 UTC, essiequoi commented on platform/about-these-features/multi-node.md
> -Example of 1 node 4 GPUs :
why this change?

2021-12-15 00:43 UTC, essiequoi commented on platform/about-these-features/multi-node.md
> +```
double check this is correct. in order for 4 nodes to launch, instance should have 1 gpu on it, since we're passing --gpus 4

2021-12-15 00:43 UTC, essiequoi commented on platform/best-practices.md
> +    3. Select "Python (.py)"
beautiful! +1 for a gif or screenshots that show the process of converting notebook to script @oojo12

2021-12-15 00:43 UTC, essiequoi commented on products/add-data-to-grid-datastores/datastore-faq.md
> +
add example usage of mount dir argument

2021-12-15 00:43 UTC, essiequoi commented on products/add-data-to-grid-datastores/datastore-faq.md
we should clarify that the max size is 1.5 TB via the CLI only. via the UI it's actually 1G @oojo12

2021-12-15 00:43 UTC, essiequoi commented on products/global-cli-configs/cli-api/grid-status.md
> +![](../../../.gitbook/assets/image%20%28123%29.png)
@oojo12 why this image? it's showing up as the hero from the marketing site

2021-12-15 00:43 UTC, essiequoi commented on products/run-run-and-sweep-github-files/faq.md
> +## How do I retain my run data?
**How do I retain my run data?**
In your response, I see answers to two different questions
1. How do I download my run/experiment artifacts? 
2. How can I download data from an Interactive Session?

We should also get into the habit of giving an example of how to do something whenever we tell users to do it. 
1. download from jupyter hub (show screenshot of where)
2. mount the data locally with grid interactive mount (give example cli command)
3. scp (give an example command)
4. pause and restart (quick gif or screenshots)

2021-12-15 00:43 UTC, essiequoi commented on products/run-run-and-sweep-github-files/faq.md
> +## Where are artifacts stored?
**Where are artifacts stored?**
Why do users need to know where they're stored? I agree that we should let them know how long artifacts are available. Maybe create a separate FAQ for that.

2021-12-15 00:43 UTC, essiequoi commented on products/run-run-and-sweep-github-files/faq.md
> +Grid by default will look for a requirements.txt file in the root directory of your project. To customize this behavior try using the `--dependency_file` flag
show example

2021-12-15 00:43 UTC, essiequoi commented on products/run-run-and-sweep-github-files/faq.md
> +
Add a clearer question here

2021-12-15 02:36 UTC, oojo12 commented on platform/about-these-features/multi-node.md
> +This is a currently an experimental feature. We welcome the community to try it out and provide feedback to <Product email here>. Multi-node or distributed training allows you to train a single model
what is the product email address?

2022-01-27 17:41 UTC, essiequoi commented
@oojo12 have these changes also been made in grid-documentation repo?

2022-01-27 17:46 UTC, oojo12 commented
> @oojo12 have these changes also been made in grid-documentation repo?

Yeah it was broken up into modular PR's there.

2022-01-28 09:57 UTC, pritamsoni-hsr commented
can we close this now? @essiequoi  @oojo12

2022-02-08 22:19 UTC, oojo12 commented
most of this was done via the other repo.

2022-02-08 22:19 UTC, closed without merging