Doc 185 document how to set up customer managed
gridai/grid-docs pull request #89
Opened 2022-02-10 13:40 UTC by oojo12

# What does this PR do? Documents how to use customer-managed BYOC

2022-02-10 13:41 UTC, oojo12 commented
Had to move from the old repo to this one due to the docs transition. Please re-review + approve if necessary.

2022-02-10 13:41 UTC, oojo12 commented
@dmitsf I addressed your comment in this version.

2022-02-10 13:43 UTC, oojo12 commented
In a separate PR we can move to make separate pages for Grid managed vs Customer managed BYOC options if this layout is confusing to anyone.

2022-02-11 13:47 UTC, nmiculinic requested changes

2022-02-11 13:47 UTC, nmiculinic commented on docs/platform/custom-cloud-credentials/adding-custom-cloud-credentials.md
> -AWS STS regional endpoints have to be enabled in the target region. Go to https://console.aws.amazon.com/iam/home#/account_settings and verify the regional endpoint is activated. In most cases your r
Why was this deleted? This is pretty tricky bug to debug.

2022-02-15 14:35 UTC, oojo12 commented
closing in favor of the modular PR's that facilitate the BYOC page redesign.

2022-02-15 14:35 UTC, closed without merging